spring.application.name=personal-knowledge-capsule

spring.datasource.url=jdbc:mysql://localhost:3306/pkc_db
spring.datasource.username=root
spring.datasource.password=2420030014@sanjay

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080
